### ISSUE TITLE
Crash on shutting down editor with Git source control plugin

### ISSUE THREAD

**Issue by sinbad** [AutoSizeComments/AutoSizeComments#23] opened 2022-11-24 16:10 UTC
I found this plugin via your other Blueprint Assist plugin, nice work!

Unfortunately once it's enabled it causes a crash when I shutdown the editor every time, linked with me also running the Git source control plugin from ProjectBorealis. Here's the stack trace:

```
UClass::GetDefaultObject(bool) Class.h:3064
[Inlined] GetDefault() UObjectGlobals.h:1565
[Inlined] FAutoSizeCommentsNotifications::ShouldShowSourceControlNotification() 0x00007ffa5d3b7de0
FAutoSizeCommentsNotifications::HandleSourceControlProviderChanged(ISourceControlProvider &,ISourceControlProvider &) 0x00007ffa5d3b7de0
[Inlined] Invoke(void (FAutoSizeCommentsNotifications::*)(ISourceControlProvider &, ISourceControlProvider &),FAutoSizeCommentsNotifications *&,ISourceControlProvider &,ISourceControlProvider &) Invoke.h:66
[Inlined] UE::Core::Private::Tuple::TTupleBase<TIntegerSequence<unsigned int> >::ApplyAfter(void (FAutoSizeCommentsNotifications::*&)(ISourceControlProvider &, ISourceControlProvider &),FAutoSizeCommentsNotifications *&,ISourceControlProvider &,ISourceControlProvider &) Tuple.h:324
TBaseRawMethodDelegateInstance<0,FAutoSizeCommentsNotifications,void __cdecl(ISourceControlProvider &,ISourceControlProvider &),FDefaultDelegateUserPolicy>::ExecuteIfSafe(ISourceControlProvider &,ISourceControlProvider &) DelegateInstancesImpl.h:467
TMulticastDelegate<void __cdecl(ISourceControlProvider &,ISourceControlProvider &),FDefaultDelegateUserPolicy>::Broadcast(ISourceControlProvider &,ISourceControlProvider &) DelegateSignatureImpl.inl:967
[Inlined] Invoke(void (FSourceControlModule::*)(const FName &, IModularFeature *),FSourceControlModule *&,const FName &,IModularFeature *&) Invoke.h:66
[Inlined] UE::Core::Private::Tuple::TTupleBase<TIntegerSequence<unsigned int> >::ApplyAfter(void (FSourceControlModule::*&)(const FName &, IModularFeature *),FSourceControlModule *&,const FName &,IModularFeature *&) Tuple.h:324
TBaseRawMethodDelegateInstance<0,FSourceControlModule,void __cdecl(FName const &,IModularFeature *),FDefaultDelegateUserPolicy>::ExecuteIfSafe(const FName &,IModularFeature *) DelegateInstancesImpl.h:467
TMulticastDelegate<void __cdecl(FName const &,IModularFeature *),FDefaultDelegateUserPolicy>::Broadcast(const FName &,IModularFeature *) DelegateSignatureImpl.inl:967
FModularFeatures::UnregisterModularFeature(FName,IModularFeature *) ModularFeatures.cpp:51
FGitSourceControlModule::ShutdownModule() GitSourceControlModule.cpp:71
[Inlined] FModuleManager::UnloadModule(FName,bool) ModuleManager.cpp:648
FModuleManager::UnloadModulesAtShutdown() ModuleManager.cpp:778
FEngineLoop::Exit() LaunchEngineLoop.cpp:4574
[Inlined] EngineExit() Launch.cpp:73
[Inlined] GuardedMain::__l2::EngineLoopCleanupGuard::{dtor}() Launch.cpp:122
GuardedMain(const wchar_t *) Launch.cpp:197
LaunchWindowsStartup(HINSTANCE__ *,HINSTANCE__ *,char *,int,const wchar_t *) LaunchWindows.cpp:272
WinMain(HINSTANCE__ *,HINSTANCE__ *,char *,int) LaunchWindows.cpp:330
[Inlined] invoke_main() 0x00007ff6e23b8736
__scrt_common_main_seh() 0x00007ff6e23b8715
<unknown> 0x00007ffb687a74b4
<unknown> 0x00007ffb691a26a1
```

Looks like `FAutoSizeCommentsNotifications::ShouldShowSourceControlNotification()` simply needs a nullptr check.

**Comment by fpwong** [comment] 2022-11-25 02:56
@sinbad @ameaninglessname Thanks for the solutions, I've added these in the latest commit. Might be some delays until this gets processed by the marketplace due to 5.1 (maybe 5 days from now?) so you may want to grab the compiled version below.

https://github.com/fpwong/AutoSizeComments/releases/tag/3.1.4

**Comment by sinbad** [comment] 2022-11-25 10:33
Excellent, thank you for such a quick turnaround - this is a good excuse for me to switch to the source version of the plugin anyway :)

**Comment by Murazaki** [comment] 2023-01-07 01:07
Error is still present for me : 

```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x0000000000000000

UnrealEditor_CoreUObject!UClass::GetDefaultObject() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Public\UObject\Class.h:3052]
UnrealEditor_AutoSizeComments!FAutoSizeCommentsNotifications::HandleSourceControlProviderChanged() [D:\home\mehdi\Dev\LunacyStudios\Maya\Plugins\AutoSizeComments\Source\AutoSizeComments\Private\AutoSizeCommentsNotifications.cpp:150]
UnrealEditor_AutoSizeComments!TBaseRawMethodDelegateInstance<0,FAutoSizeCommentsNotifications,void __cdecl(ISourceControlProvider &,ISourceControlProvider &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Apps\Epic Games\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:476]
UnrealEditor_SourceControl!TMulticastDelegate<void __cdecl(ISourceControlProvider &,ISourceControlProvider &),FDefaultDelegateUserPolicy>::Broadcast() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:975]
UnrealEditor_SourceControl!TBaseRawMethodDelegateInstance<0,FSourceControlModule,void __cdecl(FName const &,IModularFeature *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:476]
UnrealEditor_Core!TMulticastDelegate<void __cdecl(FName const &,IModularFeature *),FDefaultDelegateUserPolicy>::Broadcast() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:975]
UnrealEditor_Core!FModularFeatures::UnregisterModularFeature() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Features\ModularFeatures.cpp:70]
UnrealEditor_GitSourceControl!FGitSourceControlModule::ShutdownModule() [D:\home\mehdi\Dev\LunacyStudios\Maya\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlModule.cpp:75]
UnrealEditor_Core!FModuleManager::UnloadModulesAtShutdown() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp:816]
UnrealEditor!FEngineLoop::Exit() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4648]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:216]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

**Comment by fpwong** [comment] 2023-01-08 13:48
> Error is still present for me, running 3.1.5

Hi @Murazaki, I am also unable to reproduce this crash on my side. But I have an idea for why this may be crashing, will try push a potential fix for this soon.

**Comment by fpwong** [comment] 2023-01-11 22:59
@Murazaki Update is out (3.1.6). Let me know if this fixed the crash.

**Comment by Murazaki** [comment] 2023-01-11 23:51
I think it worked, thanks !

**Closed** 2023-01-12 00:00 UTC
Labels: bug
